.TH GENERATE.SH 1 2022-5-31 UNIX

.SH NAME
generate.sh \- project generator

.SH SYNOPSIS
.B generate.sh
[\fR<\fIcommand\fR>]

.SH DECRIPTION
.B generate.sh
creates a basic template for many different langauges

.SH OPTIONS
.TP
[\fR<\fIcommand\fR>]
the command can be one of the following \fBinstall\fR, \fBupdate\fR, \fBuninstall\fR

.SH AUTHOR
Wolfdesroyer8 <desroyerwolf8@gmail.com> and zaypers
