#!/bin/bash

# checks if user is root because commands to install need root access
if [ "$EUID" -ne 0 ]
then
  echo "Please run as root."
  exit 1
fi

# BASEDIR is where the shell script is located
BASEDIR=$(dirname "$BASH_SOURCE")

# checks if project already exists
if [ -d "/usr/local/share/projectgenerator/" ]
then
  echo "The project already exists."
  exit 1
fi

# creates library folder
mkdir "/usr/local/share/projectgenerator/"
echo "Created lib folder."
mkdir "/usr/local/share/projectgenerator/templates/"
cp -r "$BASEDIR/templates/" "/usr/local/share/projectgenerator/templates/"
echo "Added templates to lib folder."