#!/bin/bash

# checks if project already exists
if [ -d ~/.config/ProjectGenerator/ ]
then
  echo "The project already exists."
  exit 1
fi

# creates library folder
mkdir ~/.config/ProjectGenerator/
git clone git@github.com:zayndamji/project-generator.git ~/.config/ProjectGenerator/source/