#!/bin/bash

GIT_URL=github.com:zayndamji/project-generator.git
CONFIG_DIR=~/.config/ProjectGenerator

# checks if project already exists
if [ -d ~/.config/ProjectGenerator/ ]
then
  echo "The project already exists."
  exit 1
fi

# creates library folder
mkdir $CONFIG_DIR
git clone git@$GIT_URL $CONFIG_DIR/source/